channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch>=1.6.0
- torchvision
- pip
- pip:
  - scikit-learn
  - cloudpickle==1.6.0
  - boto3
  - gorilla
  - pytorch-lightning @ git+https://github.com/PyTorchLightning/pytorch-lightning.git@master

