channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.8.2
- torchvision
- pip
- pip:
  - mlflow
  - torch
  - scikit-learn
  - cloudpickle==1.6.0
  - boto3
  - transformers
  - torchtext
  - pandas
