channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch
- torchvision
- pip
- pip:
  - cloudpickle==1.6.0
  - boto3
  - matplotlib
  - pytorch-lightning>=1.2.2
  - pandas
  - gorilla
  - mlflow>=1.14.0
