channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch>=1.6.0
- torchvision
- pip
- pip:
  - cloudpickle==1.6.0
  - boto3
  - matplotlib
  - pytorch_lightning==1.2.0
  - pandas
  - gorilla
  - mlflow>=1.14.0
